# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.

on:

  # Allows you to run this workflow manually from the Actions tab

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:

  # This workflow contains a single job called "build"

  androidBuild:

    runs-on: ubuntu-latest

    strategy:

      matrix:

        arch: [release, debug]

    steps:

      - name: Checkout

        uses: actions/checkout@main

        with:

          submodules: true

      - name: Install System Dependencies

        run: |

          sudo apt-get update

          sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev g++-multilib gcc-multilib libasound2-dev libx11-dev libxext-dev libxi-dev libxrandr-dev libxinerama-dev libmbedtls-dev libpng-dev libturbojpeg-dev libuv1-dev libvorbis-dev

      - name: Setup Android NDK

        uses: nttld/setup-ndk@main

        id: setup-ndk

        with:

          ndk-version: r21e

      - name: Setup Java JDK

        uses: actions/setup-java@main

        with:

          distribution: 'zulu'

          java-version: '19'

      - name: Setup Haxe

        uses: krdlab/setup-haxe@master

        with:

          haxe-version: 4.2.5

      - name: Installing Libraries

        run: |

          haxelib --quiet install hxcpp

          haxelib --quiet install format

          haxelib --quiet install hxp

          haxelib --quiet install lime 7.9.0

          haxelib --quiet install openfl 9.1.0

          haxelib --quiet install flixel 4.11.0

          haxelib --quiet install flixel-addons 2.11.0

          haxelib --quiet install flixel-ui 2.4.0

          haxelib --quiet git linc_luajit https://github.com/AndreiRudenko/linc_luajit.git

          haxelib --quiet git hxCodec https://github.com/polybiusproxy/hxCodec.git

          haxelib --quiet git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools.git

          haxelib list

      - name: Configure Android

        run: |

          haxelib run lime setup -alias -y

          haxelib run lime config ANDROID_SDK $ANDROID_HOME

          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME

          haxelib run lime config JAVA_HOME $JAVA_HOME

          haxelib run lime config ANDROID_SETUP true

        env:

          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Building

        run: haxelib run lime build android -${{ matrix.arch }}

      - name: Upload Artifact

        uses: actions/upload-artifact@main

        with:

          name: androidBuild-${{ matrix.arch }}

          path: export/${{ matrix.arch }}/android/bin/app/build/outputs/apk/debug

          if-no-files-found: error
